# Generated by Django 4.2.5 on 2023-10-24 07:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("link", models.URLField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "news_categories_like",
                    multiselectfield.db.fields.MultiSelectField(
                        choices=[
                            ("World", "World"),
                            ("News", "News"),
                            ("Business", "Business"),
                            ("Startups", "Startups"),
                            ("Entertainment", "Entertainment"),
                            ("Sport", "Sport"),
                            ("Law", "Law"),
                            ("Education", "Education"),
                            ("Health", "Health"),
                            ("Life", "Life"),
                            ("Tourism", "Tourism"),
                            ("Science", "Science"),
                            ("Digitizing", "Digitizing"),
                            ("Car", "Car"),
                            ("Laugh", "Laugh"),
                        ],
                        max_length=200,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
