# Generated by Django 4.2.5 on 2023-11-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostAudio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name="postcheck",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="postcheck",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="deleted_at",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="is_deleted",
        ),
    ]
